language: node_js

node_js:
- '9'

cache:
  directories:
  - node_modules

sudo: enabled

install:
- npm install

script:
- if [ "$TRAVIS_BRANCH" = "master" ]; then npm run build:stage; fi
- if [ "$TRAVIS_BRANCH" = "prod" ]; then npm run build:prod; fi

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    local_dir: build
    on:
      all_branches: true

git:
  depth: 3

before_install:
- openssl aes-256-cbc -K $encrypted_10aae5acea6a_key -iv $encrypted_10aae5acea6a_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar  
